In [1]:
import numpy as np

In [19]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9,0,8,0,7,0], [6,0,5,0,4,0]])
print (b)

[[9 0 8 0 7 0]
 [6 0 5 0 4 0]]


In [4]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print (b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# How to Get Dimension of Numpy arrays
a.ndim

1

In [7]:
#Get Shape
a.shape

(3,)

In [8]:
#Prints out the number of rows and columns, 2 rows, 3 columns
b.shape

(2, 3)

In [12]:
#To know how much memory our Numpy arrays take up
#Get Type
a.dtype

dtype('int32')

In [20]:
a.dtype

dtype('int16')

In [21]:
#Get Size
a.itemsize

2

In [23]:
#Get Total size
a.size*a.itemsize

6

In [24]:
#Get Total size
a.nbytes

6

# Accessing/ Changing specific elements, rows, columns, etc

In [27]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
#TO get a specific element use [r,c]
a[1,5]

13

In [29]:
#To get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
#to get a specific column
a[:,2]

array([ 3, 10])

In [33]:
#getting a little more fancy [start index:end index:step size]
a[0,1:6:2]

array([2, 4, 6])

In [34]:
#to change something (change the 13 originally accessed)
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [36]:
#to replace the columns with 5
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [37]:
#to replace two elements in the column to 1,2
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [38]:
#a 3-d example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
#Get specific element (work outside in) (to get 4)
b[0,1,1]

4

In [42]:
#to replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Arrays

In [43]:
#To initialize an All 0s matrix use np.zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
#To do an all 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [50]:
#Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [51]:
#any other number (full_like), this allows us to take a shape that's already built
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [53]:
#to initialize a matrix of random decimal numbers between 0 and 1
np.random.rand(4,2,3)

array([[[0.00198727, 0.52062415, 0.65832631],
        [0.12981936, 0.99479098, 0.04688468]],

       [[0.41540878, 0.83411325, 0.12997155],
        [0.27955079, 0.04169828, 0.82880187]],

       [[0.40697766, 0.38186886, 0.88633703],
        [0.90170219, 0.91292189, 0.41417424]],

       [[0.25448899, 0.72684038, 0.43552124],
        [0.06148723, 0.50990575, 0.34896572]]])

In [54]:
#to pass in a shape when trying to initialize a matrix of random decimal numbers between 0 and 1
np.random.random_sample(a.shape)

array([[0.9552515 , 0.29628739, 0.14459259, 0.18959269, 0.87001486,
        0.5734225 , 0.18788752],
       [0.41980004, 0.89942539, 0.83308688, 0.48187026, 0.50562695,
        0.71814369, 0.09821958]])

In [56]:
#for random integer values
np.random.randint(7, size=(3,3))

array([[1, 1, 2],
       [3, 6, 5],
       [4, 4, 1]])

In [58]:
#for an identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
#to repeat an array few times
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=0)
print (r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [68]:
output = np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays!

In [73]:
a=np.array([1,2,3])
b=a.copy()
print(b)

[1 2 3]


In [76]:
b[0]=100
print (a)

[1 2 3]


# Mathematics capability

In [85]:
a=np.array([1,2,3,4])
print(a)

a**2

[1 2 3 4]


array([ 1,  4,  9, 16], dtype=int32)

In [86]:
#take the sin of values

np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [78]:
a+2

array([3, 4, 5, 6])

In [79]:
a-2

array([-1,  0,  1,  2])

In [80]:
a*2

array([2, 4, 6, 8])

In [81]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [83]:
b=np.array([1,0,1,0])
a+b

array([4, 4, 6, 6])

In [84]:
a**2

array([ 9, 16, 25, 36], dtype=int32)

# Linear Algebra

In [89]:
a = np.ones((2,3))
print (a)

b=np.full((3,2), 2)
print(b)

np.matmul(a,b) #matrix multiply function

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [90]:
#to find the determinant of a matrix
c=np.identity(3)  #identity matrix has a determinant of 1
np.linalg.det(c)

1.0

## Statistics

In [91]:
stats=np.array([[1,2,3],[4,5,6]])
print (stats)

[[1 2 3]
 [4 5 6]]


In [92]:
np.min(stats)

1

In [93]:
np.max(stats)

6

In [94]:
np.min(stats,axis=0)

array([1, 2, 3])

In [95]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing arrays

In [99]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [102]:
#Vertically stacking matrices or vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
#Horizontal stack

h1=np.ones((2,4))
h2=np.zeros((2,2))
print(h2)

np.hstack((h1,h2))

[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Markdown

##### Load data from file

In [107]:
filedata=np.genfromtxt('data.txt', delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

OSError: data.txt not found.

#### Boolean Masking and advanced indexing

In [ ]:
filedata[filedata>50]

In [ ]:
np.any(filedata>50, axis=0) #to see the numbers greater than 50 in the first matrix

In [108]:
## You can index with a list in Numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [109]:
a=np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25], [26,27,28,29,30]])

print (a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [111]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [113]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [119]:
a[[0,4,5], 3:] #I dont really get this

array([[ 4,  5],
       [24, 25],
       [29, 30]])